# Generated by Django 5.0.7 on 2024-11-01 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_comment_is_edited'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['id']},
        ),
    ]
